id: detonator

display:
  title: "&6Detonator"
  description:
    - "&7Ignites nearby Ignis blocks"

item:
  base_material: blaze_rod

textures:
  icon: icon.png

behavior:
  strategy: detonator
  strategy_name: Remote Detonator
  custom_data:
    range: 8.0

interactions:
  right_click:
    action: ignite_nearby
