resource-pack:
  host: "localhost"
  port: 8080
  public-url: "http://localhost:8080/resourcepack.zip"

blocks:
  - erupting-tnt
  - mimic-tnt
  - nuke
  - phantom-tnt
  - spider-storm
  - tunneling-tnt
  - wormhole-tnt
