id: nuke

display:
  title: "&aNuclear Detonation"
  description:
    - "&4Complete"
    - "&4Destruction"

block:
  placeable: true
  breakable: true

textures:
  top: nuke_top.png
  side: nuke_side.png
  bottom: nuke_bottom.png

model:
  type: "block_display"
  mode: "auto"

block_display:
  animations:
    rotate: true
    float: true
    pulse: true

behavior:
  strategy: nuclear
  fuse: 80
  radius: 15.0
  custom_data:
    power: 10.0
    multiplier: 2.0
    fire: true
    blockDamage: true
    screenShake: true