id: spider-storm

display:
  title: "&5Spider Storm"
  description:
    - "&dA powerful entity-based explosion that unleashes a swarm of"
    - "spiders on detonation. When triggered, the blast spawns multiple"
    - "spiders around the impact point, spreading them out within the area."
    - "These spiders will immediately seek out nearby players and attack on sight."
    - "Depending on configuration, the swarm may also be enhanced with effects such"
    - "as increased speed or strength, making the encounter more dangerous and unpredictable."

block:
  placeable: true
  breakable: true
  base_material: paper
  render_material: carrot_on_a_stick
  breaking:
    ticks: 35
    hit_interval_ticks: 5
    hit_sound: BLOCK_WOOL_HIT
    break_sound: BLOCK_WOOL_BREAK
    tool_ticks:
      _PICKAXE: 18
      _AXE: 24
      _SHOVEL: 24
    particles:
      hit:
        - type: DUST_PLUME
          count: 4
          offset_x: 0.30
          offset_y: 0.30
          offset_z: 0.30
          speed: 0.02
      break:
        - type: BLOCK
          block: COBWEB
          count: 26
          offset_x: 0.35
          offset_y: 0.35
          offset_z: 0.35
          speed: 0.01
        - type: SMOKE
          count: 8
          offset_x: 0.25
          offset_y: 0.25
          offset_z: 0.25
          speed: 0.01

textures:
  top: top.png
  side: side.png
  bottom: bottom.png

model:
  type: "block_display"
  mode: "auto"

block_display:
  scale: 1.01
  offset_x: 0.0
  offset_y: 0.5
  offset_z: 0.0
  view_range: 1.0
  block_light: 15
  sky_light: 15
  animations:
    rotate: true
    float: true
    pulse: true

interactions:
  left_click:
    default_action: break
    material_actions:
      - action: ignite
        materials:
          - FLINT_AND_STEEL
          - FIRE_CHARGE
          - FLINT
  right_click:
    action: ignite
    materials:
      - FLINT_AND_STEEL
      - FIRE_CHARGE
      - FLINT
  ignite:
    sound: ITEM_FLINTANDSTEEL_USE
    particles:
      - type: FLAME
        count: 12
        offset_x: 0.35
        offset_y: 0.35
        offset_z: 0.35
        speed: 0.03
      - type: SPORE_BLOSSOM_AIR
        count: 12
        offset_x: 0.45
        offset_y: 0.45
        offset_z: 0.45
        speed: 0.01

behavior:
  custom_data:
    fuse: 80
    radius: 10.0
    multiplier: 2.0
    realExplosion: false
    fire: false
    blockDamage: false
    entityPayload:
      type: SPIDER
      count: 40
      behavior: aggressive
      targetPlayers: true
